#!/usr/bin/env python3
# Copyright (c) 2025, WH, All rights reserved.
# Generates C++ source files with #embed directives for binary data.
# Usage: gen_binary_embed.py <output.cpp> <sym1:file1> [sym2:file2] ...

import sys
import os

def main():
    if len(sys.argv) < 3:
        print(f'Usage: {sys.argv[0]} <output.cpp> <sym:file> [sym:file] ...', file=sys.stderr)
        sys.exit(1)

    output_file = sys.argv[1]
    entries = sys.argv[2:]

    lines = []
    lines.append('// Auto-generated by gen_binary_embed.py - do not edit')
    lines.append('#include <cstddef>')
    lines.append('')
    lines.append('extern "C" {')

    for entry in entries:
        if ':' not in entry:
            print(f'Error: entry must be sym:file, got: {entry}', file=sys.stderr)
            sys.exit(1)

        symbol, filepath = entry.split(':', 1)

        lines.append('')
        lines.append(f'extern const unsigned char {symbol}[] = {{')
        lines.append(f'#embed "{filepath}"')
        lines.append('};')
        lines.append(f'extern const unsigned char {symbol}_end[1] = {{}};')

    lines.append('')
    lines.append('} // extern "C"')
    lines.append('')

    output_content = '\n'.join(lines)

    # only write if content changed
    if os.path.exists(output_file):
        try:
            with open(output_file, 'r') as f:
                if f.read() == output_content:
                    return
        except:
            pass

    os.makedirs(os.path.dirname(output_file) or '.', exist_ok=True)
    with open(output_file, 'w') as f:
        f.write(output_content)

if __name__ == '__main__':
    main()
