#!/usr/bin/env python3
# Copyright (c) 2026, WH, All rights reserved.
# Compiles and packs all SDLGPU shaders into .shdpk shader pack files.
#
# Finds SDLGPU_*_{v,f}.glsl in --shader-dir, compiles each to SPIR-V
# via glslc, packs GLSL source + binary into .shdpk, and writes a manifest
# file compatible with gen_binary_embed.py.
#
# Usage:
#   pack_sdlgpu_shader.py --shader-dir <dir> --output-dir <dir> --manifest <file> [--glslc <path>]
#
# .shdpk format:
#   [4B] magic "SGSH"
#   [4B] version (1)
#   [4B] num_sections
#   Per section:
#     [4B] format tag (0=GLSL, 1=SPIRV, 2=DXIL, 3=MSL)
#     [4B] data offset from start of file
#     [4B] data size
#   Section data follows

import sys
import os
import struct
import argparse
import subprocess
import glob
import re

MAGIC = b'SGSH'
VERSION = 1

FMT_GLSL = 0
FMT_SPIRV = 1
FMT_DXIL = 2
FMT_MSL = 3


def write_shdpk(output_path, sections):
    """Write a .shdpk file from a list of (format_tag, data_bytes) tuples."""
    num_sections = len(sections)
    header_size = 12 + 12 * num_sections
    offset = header_size
    section_info = []
    for fmt_tag, data in sections:
        section_info.append((fmt_tag, offset, len(data)))
        offset += len(data)

    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    with open(output_path, 'wb') as f:
        f.write(MAGIC)
        f.write(struct.pack('<I', VERSION))
        f.write(struct.pack('<I', num_sections))
        for fmt_tag, data_offset, data_size in section_info:
            f.write(struct.pack('<III', fmt_tag, data_offset, data_size))
        for _, data in sections:
            f.write(data)


def compile_glsl(glslc, glsl_path, spv_path, stage):
    """Compile a GLSL file to SPIR-V. Returns True on success."""
    stage_flag = 'vert' if stage == 'v' else 'frag'
    os.makedirs(os.path.dirname(spv_path) or '.', exist_ok=True)
    cmd = [glslc, f'-fshader-stage={stage_flag}', '--target-env=vulkan1.0', '-o', spv_path, glsl_path]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f'glslc failed for {glsl_path}:', file=sys.stderr)
        print(result.stderr, file=sys.stderr)
        return False
    return True


def find_shaders(shader_dir):
    """Find all SDLGPU_*_{v,f}.glsl files. Returns list of (name, stage, path)."""
    pattern = os.path.join(shader_dir, 'SDLGPU_*_[vf].glsl')
    shaders = []
    for path in sorted(glob.glob(pattern)):
        basename = os.path.basename(path)
        m = re.match(r'^SDLGPU_(.+)_(v|f)\.glsl$', basename)
        if m:
            shaders.append((m.group(1), m.group(2), path))
    return shaders


def main():
    parser = argparse.ArgumentParser(description='Build all SDLGPU shader packs')
    parser.add_argument('--shader-dir', required=True, help='Directory containing SDLGPU_*.glsl files')
    parser.add_argument('--output-dir', required=True, help='Output directory for .spv and .shdpk files')
    parser.add_argument('--manifest', required=True, help='Output manifest file for gen_binary_embed.py')
    parser.add_argument('--glslc', default="glslc", help='Path to glslc')
    args = parser.parse_args()

    shaders = find_shaders(args.shader_dir)
    if not shaders:
        print(f'No SDLGPU_*_{{v,f}}.glsl files found in {args.shader_dir}', file=sys.stderr)
        sys.exit(1)

    manifest_lines = [
        '# Auto-generated by pack_sdlgpu_shader.py - do not edit',
    ]
    ok = True

    for name, stage, glsl_path in shaders:
        shdpk_path = os.path.join(args.output_dir, f'SDLGPU_{name}_{stage}.shdpk')
        symbol = f'SDLGPU_{name}_{stage}sh'

        # compile GLSL -> SPIR-V -> .shdpk
        spv_path = os.path.join(args.output_dir, f'SDLGPU_{name}_{stage}.spv')
        if not compile_glsl(args.glslc, glsl_path, spv_path, stage):
            ok = False
            continue

        with open(glsl_path, 'rb') as f:
            glsl_data = f.read()
        with open(spv_path, 'rb') as f:
            spv_data = f.read()

        write_shdpk(shdpk_path, [(FMT_GLSL, glsl_data), (FMT_SPIRV, spv_data)])

        manifest_lines.append(f'{symbol} : {shdpk_path}')

    if not ok:
        sys.exit(1)

    os.makedirs(os.path.dirname(args.manifest) or '.', exist_ok=True)
    with open(args.manifest, 'w') as f:
        f.write('\n'.join(manifest_lines) + '\n')


if __name__ == '__main__':
    main()
