#pragma once
// Copyright (c) 2016, PG, All rights reserved.
#ifndef SDL_scancode_h_
extern "C" {
typedef enum SDL_Scancode {
#define EN(key__, num__) SDL_SCANCODE_##key__ = (num__),
    // clang-format off
EN(UNKNOWN, 0) EN(H, 11) EN(P, 19) EN(X, 27) EN(6, 35)
EN(A, 4)       EN(I, 12) EN(Q, 20) EN(Y, 28) EN(7, 36)
EN(B, 5)       EN(J, 13) EN(R, 21) EN(Z, 29) EN(8, 37)
EN(C, 6)       EN(K, 14) EN(S, 22) EN(1, 30) EN(9, 38)
EN(D, 7)       EN(L, 15) EN(T, 23) EN(2, 31) EN(0, 39)
EN(E, 8)       EN(M, 16) EN(U, 24) EN(3, 32) EN(RETURN, 40)
EN(F, 9)       EN(N, 17) EN(V, 25) EN(4, 33) EN(ESCAPE, 41)
EN(G, 10)      EN(O, 18) EN(W, 26) EN(5, 34) EN(BACKSPACE, 42)

EN(TAB, 43)          EN(SEMICOLON, 51)  EN(F2, 59) EN(F10, 67)         EN(PAGEUP, 75)
EN(SPACE, 44)        EN(APOSTROPHE, 52) EN(F3, 60) EN(F11, 68)         EN(DELETE, 76)
EN(MINUS, 45)        EN(GRAVE, 53)      EN(F4, 61) EN(F12, 69)         EN(END, 77)
EN(EQUALS, 46)       EN(COMMA, 54)      EN(F5, 62) EN(PRINTSCREEN, 70) EN(PAGEDOWN, 78)
EN(LEFTBRACKET, 47)  EN(PERIOD, 55)     EN(F6, 63) EN(SCROLLLOCK, 71)  EN(RIGHT, 79)
EN(RIGHTBRACKET, 48) EN(SLASH, 56)      EN(F7, 64) EN(PAUSE, 72)       EN(LEFT, 80)
EN(BACKSLASH, 49)    EN(CAPSLOCK, 57)   EN(F8, 65) EN(INSERT, 73)      EN(DOWN, 81)
EN(NONUSHASH, 50)    EN(F1, 58)         EN(F9, 66) EN(HOME, 74)        EN(UP, 82)

EN(NUMLOCKCLEAR, 83) EN(KP_3, 91) EN(KP_PERIOD, 99)       EN(F16, 107) EN(F24, 115)
EN(KP_DIVIDE, 84)    EN(KP_4, 92) EN(NONUSBACKSLASH, 100) EN(F17, 108) EN(EXECUTE, 116)
EN(KP_MULTIPLY, 85)  EN(KP_5, 93) EN(APPLICATION, 101)    EN(F18, 109) EN(HELP, 117)
EN(KP_MINUS, 86)     EN(KP_6, 94) EN(POWER, 102)          EN(F19, 110) EN(MENU, 118)
EN(KP_PLUS, 87)      EN(KP_7, 95) EN(KP_EQUALS, 103)      EN(F20, 111) EN(SELECT, 119)
EN(KP_ENTER, 88)     EN(KP_8, 96) EN(F13, 104)            EN(F21, 112) EN(STOP, 120)
EN(KP_1, 89)         EN(KP_9, 97) EN(F14, 105)            EN(F22, 113) EN(AGAIN, 121)
EN(KP_2, 90)         EN(KP_0, 98) EN(F15, 106)            EN(F23, 114) EN(UNDO, 122)

EN(CUT, 123)        EN(KP_EQUALSAS400, 134) EN(INTERNATIONAL8, 142) EN(LANG7, 150)    EN(RETURN2, 158)
EN(COPY, 124)       EN(INTERNATIONAL1, 135) EN(INTERNATIONAL9, 143) EN(LANG8, 151)    EN(SEPARATOR, 159)
EN(PASTE, 125)      EN(INTERNATIONAL2, 136) EN(LANG1, 144)          EN(LANG9, 152)    EN(OUT, 160)
EN(FIND, 126)       EN(INTERNATIONAL3, 137) EN(LANG2, 145)          EN(ALTERASE, 153) EN(OPER, 161)
EN(MUTE, 127)       EN(INTERNATIONAL4, 138) EN(LANG3, 146)          EN(SYSREQ, 154)   EN(CLEARAGAIN, 162)
EN(VOLUMEUP, 128)   EN(INTERNATIONAL5, 139) EN(LANG4, 147)          EN(CANCEL, 155)   EN(CRSEL, 163)
EN(VOLUMEDOWN, 129) EN(INTERNATIONAL6, 140) EN(LANG5, 148)          EN(CLEAR, 156)    EN(EXSEL, 164)
EN(KP_COMMA, 133)   EN(INTERNATIONAL7, 141) EN(LANG6, 149)          EN(PRIOR, 157)    EN(KP_00, 176)

EN(KP_000, 177)             EN(KP_RIGHTBRACE, 185) EN(KP_F, 193)            EN(KP_VERTICALBAR, 201)    EN(KP_MEMRECALL, 209)
EN(THOUSANDSSEPARATOR, 178) EN(KP_TAB, 186)        EN(KP_XOR, 194)          EN(KP_DBLVERTICALBAR, 202) EN(KP_MEMCLEAR, 210)
EN(DECIMALSEPARATOR, 179)   EN(KP_BACKSPACE, 187)  EN(KP_POWER, 195)        EN(KP_COLON, 203)          EN(KP_MEMADD, 211)
EN(CURRENCYUNIT, 180)       EN(KP_A, 188)          EN(KP_PERCENT, 196)      EN(KP_HASH, 204)           EN(KP_MEMSUBTRACT, 212)
EN(CURRENCYSUBUNIT, 181)    EN(KP_B, 189)          EN(KP_LESS, 197)         EN(KP_SPACE, 205)          EN(KP_MEMMULTIPLY, 213)
EN(KP_LEFTPAREN, 182)       EN(KP_C, 190)          EN(KP_GREATER, 198)      EN(KP_AT, 206)             EN(KP_MEMDIVIDE, 214)
EN(KP_RIGHTPAREN, 183)      EN(KP_D, 191)          EN(KP_AMPERSAND, 199)    EN(KP_EXCLAM, 207)         EN(KP_PLUSMINUS, 215)
EN(KP_LEFTBRACE, 184)       EN(KP_E, 192)          EN(KP_DBLAMPERSAND, 200) EN(KP_MEMSTORE, 208)       EN(KP_CLEAR, 216)

EN(KP_CLEARENTRY, 217)  EN(LGUI, 227)   EN(CHANNEL_INCREMENT, 260)  EN(MEDIA_PREVIOUS_TRACK, 268) EN(AC_EXIT, 276)
EN(KP_BINARY, 218)      EN(RCTRL, 228)  EN(CHANNEL_DECREMENT, 261)  EN(MEDIA_STOP, 269)           EN(AC_SAVE, 277)
EN(KP_OCTAL, 219)       EN(RSHIFT, 229) EN(MEDIA_PLAY, 262)         EN(MEDIA_EJECT, 270)          EN(AC_PRINT, 278)
EN(KP_DECIMAL, 220)     EN(RALT, 230)   EN(MEDIA_PAUSE, 263)        EN(MEDIA_PLAY_PAUSE, 271)     EN(AC_PROPERTIES, 279)
EN(KP_HEXADECIMAL, 221) EN(RGUI, 231)   EN(MEDIA_RECORD, 264)       EN(MEDIA_SELECT, 272)         EN(AC_SEARCH, 280)
EN(LCTRL, 224)          EN(MODE, 257)   EN(MEDIA_FAST_FORWARD, 265) EN(AC_NEW, 273)               EN(AC_HOME, 281)
EN(LSHIFT, 225)         EN(SLEEP, 258)  EN(MEDIA_REWIND, 266)       EN(AC_OPEN, 274)              EN(AC_BACK, 282)
EN(LALT, 226)           EN(WAKE, 259)   EN(MEDIA_NEXT_TRACK, 267)   EN(AC_CLOSE, 275)             EN(AC_FORWARD, 283)

EN(AC_STOP, 284)
EN(AC_REFRESH, 285)
EN(AC_BOOKMARKS, 286)
EN(SOFTLEFT, 287)
EN(SOFTRIGHT, 288)
EN(CALL, 289)
EN(RESERVED, 400)
EN(COUNT, 51)
// clang-format on
#undef EN
} SDL_Scancode;
}
#endif  // SDL_scancode_h_

#include <vector>
#include "types.h"

class ConVar;

class KeyBindings {
   public:
    static std::vector<ConVar*> ALL;
    static i32 old_keycode_to_sdl_keycode(i32 key);
};

// alphabet
#define KEY_A SDL_SCANCODE_A
#define KEY_B SDL_SCANCODE_B
#define KEY_C SDL_SCANCODE_C
#define KEY_D SDL_SCANCODE_D
#define KEY_E SDL_SCANCODE_E
#define KEY_F SDL_SCANCODE_F
#define KEY_G SDL_SCANCODE_G
#define KEY_H SDL_SCANCODE_H
#define KEY_I SDL_SCANCODE_I
#define KEY_J SDL_SCANCODE_J
#define KEY_K SDL_SCANCODE_K
#define KEY_L SDL_SCANCODE_L
#define KEY_M SDL_SCANCODE_M
#define KEY_N SDL_SCANCODE_N
#define KEY_O SDL_SCANCODE_O
#define KEY_P SDL_SCANCODE_P
#define KEY_Q SDL_SCANCODE_Q
#define KEY_R SDL_SCANCODE_R
#define KEY_S SDL_SCANCODE_S
#define KEY_T SDL_SCANCODE_T
#define KEY_U SDL_SCANCODE_U
#define KEY_V SDL_SCANCODE_V
#define KEY_W SDL_SCANCODE_W
#define KEY_X SDL_SCANCODE_X
#define KEY_Y SDL_SCANCODE_Y
#define KEY_Z SDL_SCANCODE_Z

// numbers
#define KEY_0 SDL_SCANCODE_0
#define KEY_1 SDL_SCANCODE_1
#define KEY_2 SDL_SCANCODE_2
#define KEY_3 SDL_SCANCODE_3
#define KEY_4 SDL_SCANCODE_4
#define KEY_5 SDL_SCANCODE_5
#define KEY_6 SDL_SCANCODE_6
#define KEY_7 SDL_SCANCODE_7
#define KEY_8 SDL_SCANCODE_8
#define KEY_9 SDL_SCANCODE_9

// numpad
#define KEY_NUMPAD0 SDL_SCANCODE_KP_0
#define KEY_NUMPAD1 SDL_SCANCODE_KP_1
#define KEY_NUMPAD2 SDL_SCANCODE_KP_2
#define KEY_NUMPAD3 SDL_SCANCODE_KP_3
#define KEY_NUMPAD4 SDL_SCANCODE_KP_4
#define KEY_NUMPAD5 SDL_SCANCODE_KP_5
#define KEY_NUMPAD6 SDL_SCANCODE_KP_6
#define KEY_NUMPAD7 SDL_SCANCODE_KP_7
#define KEY_NUMPAD8 SDL_SCANCODE_KP_8
#define KEY_NUMPAD9 SDL_SCANCODE_KP_9
#define KEY_MULTIPLY SDL_SCANCODE_KP_MULTIPLY
#define KEY_ADD SDL_SCANCODE_KP_PLUS
#define KEY_SEPARATOR SDL_SCANCODE_KP_EQUALS
#define KEY_SUBTRACT SDL_SCANCODE_KP_MINUS
#define KEY_DECIMAL SDL_SCANCODE_KP_DECIMAL
#define KEY_DIVIDE SDL_SCANCODE_KP_DIVIDE

// function keys
#define KEY_F1 SDL_SCANCODE_F1
#define KEY_F2 SDL_SCANCODE_F2
#define KEY_F3 SDL_SCANCODE_F3
#define KEY_F4 SDL_SCANCODE_F4
#define KEY_F5 SDL_SCANCODE_F5
#define KEY_F6 SDL_SCANCODE_F6
#define KEY_F7 SDL_SCANCODE_F7
#define KEY_F8 SDL_SCANCODE_F8
#define KEY_F9 SDL_SCANCODE_F9
#define KEY_F10 SDL_SCANCODE_F10
#define KEY_F11 SDL_SCANCODE_F11
#define KEY_F12 SDL_SCANCODE_F12

// arrow keys
#define KEY_LEFT SDL_SCANCODE_LEFT
#define KEY_RIGHT SDL_SCANCODE_RIGHT
#define KEY_UP SDL_SCANCODE_UP
#define KEY_DOWN SDL_SCANCODE_DOWN

// special keys
#define KEY_TAB SDL_SCANCODE_TAB
#define KEY_NUMPAD_ENTER SDL_SCANCODE_KP_ENTER
#define KEY_ENTER SDL_SCANCODE_RETURN
#define KEY_LSHIFT SDL_SCANCODE_LSHIFT
#define KEY_RSHIFT SDL_SCANCODE_RSHIFT
#define KEY_LCONTROL SDL_SCANCODE_LCTRL
#define KEY_RCONTROL SDL_SCANCODE_RCTRL
#define KEY_LALT SDL_SCANCODE_LALT
#define KEY_RALT SDL_SCANCODE_RALT
#define KEY_ESCAPE SDL_SCANCODE_ESCAPE
#define KEY_TILDE SDL_SCANCODE_GRAVE
#define KEY_SPACE SDL_SCANCODE_SPACE
#define KEY_BACKSPACE SDL_SCANCODE_BACKSPACE
#define KEY_END SDL_SCANCODE_END
#define KEY_INSERT SDL_SCANCODE_INSERT
#define KEY_DELETE SDL_SCANCODE_DELETE
#define KEY_HELP SDL_SCANCODE_HELP
#define KEY_HOME SDL_SCANCODE_HOME
#define KEY_LSUPER SDL_SCANCODE_LGUI
#define KEY_RSUPER SDL_SCANCODE_RGUI
#define KEY_PAGEUP SDL_SCANCODE_PAGEUP
#define KEY_PAGEDOWN SDL_SCANCODE_PAGEDOWN
