name: win-multiarch
on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

env:
  CCACHE_DIR: /tmp/.ccache

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:multilib-devel
    strategy:
      matrix:
        arch: [x64, x32]
        include:
          - arch: x64
            host: x86_64-w64-mingw32
          - arch: x32
            host: i686-w64-mingw32
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v4

      - name: Set up build directory
        run: |
          mkdir -p "$(pwd)"/build-out/build
          mkdir -p ${{ env.CCACHE_DIR }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            build-out/build/deps
            build-aux/cache
          key: deps-win-${{ matrix.arch }}-${{ hashFiles('configure.ac', 'Makefile.am') }}
          restore-keys: |
            deps-win-${{ matrix.arch }}-${{ hashFiles('configure.ac', 'Makefile.am') }}

      - name: ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-win-${{ matrix.arch }}-${{ github.sha }}
          restore-keys: |
            ccache-win-${{ matrix.arch }}-

      # unfortunately, wine 10.14 is broken, so use a prebuilt wine-stable instead
      - name: Add chaotic-aur pacman repository
        run: |
          pacman-key --init
          pacman-key --populate archlinux
          pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
          pacman-key --lsign-key 3056513887B78AEB
          pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'
          pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
          echo -e "\n[chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist" >> /etc/pacman.conf

      - name: Installing dependencies
        run: |
          pacman -Syu --noconfirm base-devel libx11 libxi glu \
            libjpeg-turbo libglvnd freetype2 sdl3 zlib wget \
            cmake meson nasm git autoconf automake libtool autoconf-archive \
            mingw-w64-gcc ccache unzip wine-stable
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Building neosu
        run: |
          MAKEFLAGS="-j$(nproc)" ./autogen.sh
          cd build-out && \
          MAKEFLAGS="-j$(nproc)" ../configure \
            ${{ (github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/dev') && '--disable-strip' || '' }} \
            --with-audio="bass,soloud" --host=${{ matrix.host }} && \
          CCACHE_DIR="${{ env.CCACHE_DIR }}" MAKEFLAGS="-j$(nproc)" make install

      - uses: actions/upload-artifact@v4
        with:
          name: neosu-win-${{ matrix.arch }}
          path: build-out/dist
